version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: es01
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
      XPACK_MONITORING_ENABLED: "true"
    networks:
      - esnet

  logstash:
    image: docker.elastic.co/logstash/logstash:7.3.1
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline/
      - ./Takeout:/takeout
      - ./mappings:/takeout/mappings
    ports:
      - 9600:9600
    environment:
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: http://es01:9200
      CONFIG_RELOAD_AUTOMATIC: "true"
      CONFIG_SUPPORT_ESCAPES: "true"
      # LOG_LEVEL: "debug"
    networks:
      - esnet
    depends_on:
      - es01

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:

